---
- hosts: all
  vars_files:
    - vars/secrets.yml
    - vars/all_vars.yml
  tasks:
    - name: Use encrypted variable
      debug:
        msg: "The secret value is {{ user_all_vm.name }}"
        
