---
- name: SSH copy 
  hosts: linux
  gather_facts: false
  # Use 'become: true' if you need root privileges to manage the user's home directory
  # become: true
  
  tasks:
    - name: Ensure the SSH key is present in the authorized_keys file
      ansible.posix.authorized_key:
        user: "<remote_username>"
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
        manage_dir: true 

